"""Deterministic generator for fixtures/line_days.csv (synthetic, seeded).

    python fixtures/generate_line_days.py                 # rewrite fixtures/line_days.csv
    python fixtures/generate_line_days.py --out other.csv # write elsewhere

Standard library only, so the committed CSV can be regenerated byte for byte
on any Python 3.12 without the lab's requirements. Every random draw comes
from random.Random(SEED).random(); the normal and Poisson draws are built from
it here (Box-Muller and Knuth's product method) rather than taken from a
library, so no library version can change the numbers.

What the generator writes, one row per calendar day of fictional Cinderline
Components' bracket line L4 from Monday 2026-06-01 to Friday 2026-08-21 (82 days):

  planned_hours  the published calendar: 16 on Monday-Friday (two shifts),
                 8 on Saturday (one shift), 0 on Sunday (closed). Known weeks
                 in advance.
  run_hours      hours the line actually ran: planned hours minus a random
                 stoppage of up to 1 hour (0.5 on Saturday), rounded to a
                 quarter hour. Recorded when the day ends, so it is NOT known
                 at a forecast origin.
  units          good and bad units produced: units per run hour (25.0 on
                 Monday, 26.5 Tuesday-Friday, 23.0 Saturday) times run_hours
                 plus normal noise with standard deviation 8, rounded.
  defects        defective units found at end-of-line inspection: Poisson with
                 mean 0.02 x units x a day-level multiplier drawn uniformly
                 from [0.55, 1.45] (real defect counts vary more than a Poisson
                 count does), plus the injected excess on bad-lot days.
  event          the synthetic ground truth, used only to evaluate the anomaly
                 threshold: none, bad_lot (extra defects injected) or
                 breakdown (run_hours forced to 5.5).

The seed and the injections were chosen, from a handful of candidates, so that
the backtest and the threshold table show the lab's trade-offs; the selection
is disclosed in DATA.md. Nothing here is a measurement of a real line.
"""
from __future__ import annotations

import argparse
import datetime as dt
import math
from pathlib import Path
import random

SEED = 47
START = dt.date(2026, 6, 1)
DAYS = 82
DEFECT_RATE = 0.02
NOISE_SD = 8.0
DISPERSION = 0.45            # multiplier drawn from [1 - 0.45, 1 + 0.45]
PER_HOUR = {0: 25.0, 5: 23.0}  # weekday() -> units per run hour; others 26.5
BREAKDOWN = {79: 5.5}        # day index -> forced run_hours (Wed 2026-08-19)
BAD_LOTS = {36: 5, 45: 8, 56: 11, 66: 15, 71: 22}  # day index -> injected extra defects
WEEKDAYS = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
HEADER = "date,weekday,planned_hours,run_hours,units,defects,event"


def normal(rng: random.Random) -> float:
    """One standard normal draw from two uniforms (Box-Muller, cosine branch)."""
    u1, u2 = rng.random(), rng.random()
    return math.sqrt(-2.0 * math.log(1.0 - u1)) * math.cos(2.0 * math.pi * u2)


def poisson(rng: random.Random, mean: float) -> int:
    """Knuth's product method; fine for the small means used here."""
    limit, k, product = math.exp(-mean), 0, 1.0
    while True:
        k += 1
        product *= rng.random()
        if product <= limit:
            return k - 1


def rows() -> list[str]:
    rng = random.Random(SEED)
    out = [HEADER]
    for i in range(DAYS):
        day = START + dt.timedelta(days=i)
        wd = day.weekday()
        if wd == 6:  # Sunday: closed, no draws consumed
            out.append(f"{day.isoformat()},Sun,0,0.00,0,0,none")
            continue
        planned = 8.0 if wd == 5 else 16.0
        stoppage = rng.random() * (0.5 if wd == 5 else 1.0)
        run = round((planned - stoppage) * 4) / 4
        event = "none"
        if i in BREAKDOWN:
            run, event = BREAKDOWN[i], "breakdown"
        units = max(0, round(PER_HOUR.get(wd, 26.5) * run + NOISE_SD * normal(rng)))
        multiplier = 1.0 + DISPERSION * (rng.random() - 0.5) * 2
        defects = poisson(rng, DEFECT_RATE * units * multiplier)
        if i in BAD_LOTS:
            defects, event = defects + BAD_LOTS[i], "bad_lot"
        out.append(f"{day.isoformat()},{WEEKDAYS[wd]},{planned:.0f},{run:.2f},{units},{defects},{event}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path(__file__).with_name("line_days.csv"))
    args = parser.parse_args()
    args.out.write_text("\n".join(rows()) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
