#!/usr/bin/env python3
"""Write the claim blocker report from the claim ledger; do not infer any verdict.

Usage: python scripts/academy-claim-leads.py [--write] [--check]

Reads docs/academy/CLAIM-REVIEW.json (generated by academy-claim-review.py) and
docs/academy/CLAIM-REVIEWS.json (the explicit decisions) and writes
docs/academy/CLAIM-LEADS.md: every documented claim that is not yet reviewed,
grouped by module, with the gap its decision records. A claim with no decision
is listed by count per module. With --check the committed report must match.
"""
import argparse
import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'docs/academy/CLAIM-LEADS.md'


def build():
    ledger = json.loads((ROOT / 'docs/academy/CLAIM-REVIEW.json').read_text())
    decisions = {d['id']: d for d in json.loads((ROOT / 'docs/academy/CLAIM-REVIEWS.json').read_text())['claims']}
    by_module = collections.defaultdict(list)
    for c in ledger['claims']:
        by_module[c.get('moduleId') or '(course level)'].append(c)
    undecided = collections.Counter()
    decided_pending = collections.defaultdict(list)
    partial = collections.defaultdict(list)
    for module, claims in by_module.items():
        for c in claims:
            d = decisions.get(c['id'])
            if c['status'] == 'pending-claim-review':
                if d:
                    decided_pending[module].append((c, d))
                else:
                    undecided[module] += 1
            elif c['status'] == 'partial':
                partial[module].append((c, d))
    totals = ledger['totals']['byStatus']
    lines = [
        '# Claim leads and blocker report',
        '',
        'Generated by `python scripts/academy-claim-leads.py --write` from',
        '[`CLAIM-REVIEW.json`](CLAIM-REVIEW.json) and [`CLAIM-REVIEWS.json`](CLAIM-REVIEWS.json).',
        'It lists every documented claim that is not yet reviewed and, where a decision',
        'exists, the gap that decision records: what is supported, what is not, and',
        'which source would settle it. Pending means unfinished work, not an assertion',
        'that a source is inaccessible; partial means some assertions of the claim as',
        'taught are supported and others are not. Nothing here is a verdict on a claim',
        'without a decision.',
        '',
        '## Totals',
        '',
        '| Status | Claims |',
        '|---|---:|',
    ]
    for status in ('reviewed', 'corrected-and-reviewed', 'partial', 'pending-claim-review', 'retained-prior-evidence'):
        lines.append(f'| {status} | {totals.get(status, 0)} |')
    lines += ['', f'Of the {totals.get("pending-claim-review", 0)} pending claims, '
              f'{sum(undecided.values())} have no decision yet and '
              f'{sum(len(v) for v in decided_pending.values())} were reviewed without a decisive source.', '',
              '## Modules without a claim-level review', '',
              '| Module | Pending claims without a decision |', '|---|---:|']
    for module in sorted(undecided):
        lines.append(f'| {module} | {undecided[module]} |')

    def entries(title, groups):
        out = ['', f'## {title}', '']
        for module in sorted(groups):
            out += [f'### {module}', '']
            for c, d in sorted(groups[module], key=lambda x: x[0]['id']):
                gap = (d or {}).get('gaps') or (d or {}).get('finding') or 'No decision recorded.'
                gap = gap if isinstance(gap, str) else json.dumps(gap, ensure_ascii=False)
                who = f" ({d['reviewedAt']})" if d else ''
                out.append(f"- `{c['id']}`{who}: {' '.join(gap.split())}")
            out.append('')
        return out

    lines += entries('Reviewed but still pending', decided_pending)
    lines += entries('Partial', partial)
    return '\n'.join(lines).rstrip() + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = build()
    if args.write:
        OUT.write_text(text)
    if args.check and (not OUT.exists() or OUT.read_text() != text):
        raise SystemExit('Claim leads report is stale')
    print(f'{OUT.relative_to(ROOT)}: {len(text.splitlines())} lines')


if __name__ == '__main__':
    main()
